一、项目结构
1、commonTools:公共工具
2、goServer:一些简单的go服务器
	chatServer：聊天服务器
	fileServer：文件服务器
	goServer:业务处理服务器
	httpServer：静态页面服务器
	goServerModel：通用Model
	goClient：客户端
	webSite:静态页面
3、test:测试简单Demo
4、vendor:引用项目