CREATE TABLE IF NOT EXISTS `testTable`(
`de` bit(1) NOT NULL DEFAULT b'0' COMMENT '',
`Id` int NOT NULL DEFAULT 1 COMMENT '',
`Name` varchar(255) NULL DEFAULT NULL COMMENT '312312',
PRIMARY KEY(`Id`)
)
COMMENT='31231';

CREATE TABLE IF NOT EXISTS `testTable_copy1`(
`Id` int NOT NULL DEFAULT 1 COMMENT '',
`Name` varchar(255) NOT NULL DEFAULT 'de' COMMENT '312312',
PRIMARY KEY(`Id`)
)
COMMENT='3123';

