package consts

//----------------常量------------------------
const (
	UserID            = "UserID"
	UserName          = "UserName"
	FullName          = "FullName"
	Password          = "Password"
	PwdExpiredTime    = "PwdExpiredTime"
	Sex               = "Sex"
	Phone             = "Phone"
	Email             = "Email"
	Status            = "Status"
	LoginCount        = "LoginCount"
	LastLoginTime     = "LastLoginTime"
	LastLoginIP       = "LastLoginIP"
	RoleIDs           = "RoleIDs"
	CreateTime        = "CreateTime"
	MenuScript        = "MenuScript"
	ID                = "ID"
	UserId            = "UserId"
	Title             = "Title"
	Content           = "Content"
	Tag               = "Tag"
	ATUsers           = "ATUsers"
	BlogType          = "BlogType"
	CrDate            = "CrDate"
	ReDate            = "ReDate"
	Token             = "Token"
	FileServerAddress = "FileServerAddress"
	GoServerAddress   = "GoServerAddress"
	ChatServerAddress = "ChatServerAddress"
	Online            = "Online"
	FileName          = "FileName"
	ModTime          = "ModTime"
)
